import { PresentationConfig } from "@/types/presentation";

export const presentationConfig: PresentationConfig = {
  title: "An Architectural Approach to Cross-Domain Data Interoperability at NOAA Fisheries",
  shortTitle: "Data Mesh Reference Architecture",
  subtitle: "Applying the Data Mesh Paradigm in Google Cloud Platform",
  author: "NOAA Enterprise Data Management Workshop",
  version: "1.0.0",
  lastUpdated: "2026",
  slides: [
    {
      id: "slide-1",
      type: "title",
      title: "An Architectural Approach to Cross-Domain Data Interoperability at NOAA Fisheries",
      subtitle: "NOAA Enterprise Data Management Workshop 2026",
      category: "ENTERPRISE ARCHITECTURE",
      author: "Joshua Lee",
      authorRole: "",
      avatarPath: "/avatar.jpg",
      date: "2026",
      tags: ["Data Mesh", "Interoperability", "Google Cloud Platform"],
      logoPath: "/titleSlide.svg",
      notes: "Title cover slide showcasing custom vector logo and Coral accent line.",
    },
    {
      id: "slide-2",
      type: "split",
      title: "The Structural Challenge",
      subtitle: "Balancing distributed autonomy with enterprise-wide integration mandates across a highly federated organization.",
      category: "THE PROBLEM",
      bullets: [
        "NOAA Fisheries operates through a highly federated structure across distinct geographical jurisdictions.",
        "Data ecosystems rely on localized expertise to support binding regulatory decisions under the Magnuson-Stevens Act.",
        "Federal mandates (NIST 800-53, OPEN Government Data Act) require robust security and enterprise accessibility.",
        "Tension exists between keeping data close to its creators and ensuring cross-domain interoperability.",
      ],
      mediaType: "card",
      mediaCardTitle: "NOAA Fisheries Distributed Structure",
      mediaCardItems: [
        { label: "Fishery Management Councils", value: "8" },
        { label: "Regional Offices", value: "5" },
        { label: "Science Centers", value: "6" },
      ],
      mediaCaption: "Our highly federated structure requires a data architecture that scales organizational complexity, not just data volume.",
    },
    {
      id: "slide-3",
      type: "featureGrid",
      title: "The Evolution of Big Data",
      subtitle: "Searching for patterns that scale organizational complexity, not just data volume.",
      category: "ARCHITECTURAL CONTEXT",
      features: [
        {
          id: "f-1",
          title: "Data Warehouse",
          description: "Provided consistency through centralized schema enforcement but created massive bottlenecks as organizations grew.",
          iconName: "Database",
          badge: "Centralized",
          accentColor: "coral",
        },
        {
          id: "f-2",
          title: "Data Lake",
          description: "Democratized access through schema-on-read flexibility, but often produced ungoverned 'data swamps'.",
          iconName: "Waves",
          badge: "Fragmented",
          accentColor: "seagrass",
        },
        {
          id: "f-3",
          title: "Data Mesh",
          description: "Synthesizes the governance strengths of warehouses with the scalability of lakes by distributing accountability.",
          iconName: "Network",
          badge: "Federated",
          accentColor: "skygold",
        },
      ],
    },
    {
      id: "slide-4",
      type: "quote",
      title: "Domain Ownership",
      subtitle: "Rethinking how we decompose analytical data architecture.",
      category: "FOUNDATIONAL PRINCIPLES",
      quote: "Mission domains, not technology layers, are the correct unit of decomposition for analytical data architecture.",
      author: "Conway's Law & Parnas Decomposition",
      authorTitle: "Domain-Driven Design (Evans)",
      organization: "Software Engineering Principles",
      notes: "Reference bounded context and ubiquitous language.",
    },
    {
      id: "slide-5",
      type: "featureGrid",
      title: "Four Principles of Data Mesh",
      subtitle: "An interdependent system for decentralized data management.",
      category: "DATA MESH CORE",
      features: [
        {
          id: "f-1",
          title: "Domain Ownership",
          description: "Distributes accountability to the mission domains that generate and understand the data.",
          iconName: "Users",
          badge: "Accountability",
          accentColor: "noaa",
        },
        {
          id: "f-2",
          title: "Data as a Product",
          description: "Transforms data into an actively managed offering with defined consumers and quality guarantees.",
          iconName: "Package",
          badge: "Quality",
          accentColor: "coral",
        },
        {
          id: "f-3",
          title: "Self-serve Platform",
          description: "Provides shared GCP infrastructure that makes domain autonomy feasible at scale.",
          iconName: "Server",
          badge: "Infrastructure",
          accentColor: "skygold",
        },
        {
          id: "f-4",
          title: "Computational Governance",
          description: "Coordinates decentralized ownership through automated rules rather than manual gatekeeping.",
          iconName: "Shield",
          badge: "Compliance",
          accentColor: "seagrass",
        },
      ],
    },
    {
      id: "slide-6",
      type: "split",
      title: "Electronic Monitoring Case Study",
      subtitle: "Applying data mesh principles to a concrete federal regulatory context.",
      category: "CASE STUDY",
      bullets: [
        "Electronic Monitoring (EM) systems generate terabytes of video processed into structured data products.",
        "Discoverable via Dataplex and addressable via BigQuery with explicit Service Level Objectives.",
        "Inherits NIST 800-53 security controls directly from the underlying GCP platform architecture.",
        "Computational data governance enforces MSA confidentiality provisions automatically.",
      ],
      mediaType: "card",
      mediaCardTitle: "Data as a Product (EM)",
      mediaCardItems: [
        { label: "Trustworthy", value: "99% Completeness SLO" },
        { label: "Freshness", value: "30-day Guarantee" },
        { label: "Secure", value: "IAM Row-Level Access" },
        { label: "Platform", value: "Google Cloud" },
      ],
      mediaCaption: "EM proves that federal security requirements can be satisfied through automated platform inheritance.",
    },
    {
      id: "slide-7",
      type: "featureGrid",
      title: "The Unified Cloud Estate",
      subtitle: "Connecting distributed products via a pragmatic federation without forcing a single platform.",
      category: "ENTERPRISE FEDERATION",
      features: [
        {
          id: "f-1",
          title: "Standardized Contracts",
          description: "Data products specify schema and quality standards in platform-agnostic formats.",
          iconName: "FileText",
          badge: "Interoperability",
          accentColor: "skygold",
        },
        {
          id: "f-2",
          title: "Federated Catalog",
          description: "Aggregating metadata from distinct organizational catalogs for enterprise-wide discovery.",
          iconName: "Search",
          badge: "Discovery",
          accentColor: "seagrass",
        },
        {
          id: "f-3",
          title: "Cross-Cloud Gateways",
          description: "Managing query routing and identity translation across different cloud providers.",
          iconName: "Cloud",
          badge: "Access",
          accentColor: "coral",
        },
        {
          id: "f-4",
          title: "Enterprise Governance",
          description: "A council establishing interoperability standards while preserving organizational autonomy.",
          iconName: "Scale",
          badge: "Policy",
          accentColor: "noaa",
        },
      ],
    },
    {
      id: "slide-8",
      type: "split",
      title: "Migration Strategy",
      subtitle: "Evolutionary adoption patterns for transitioning legacy systems to the mesh.",
      category: "ADOPTION",
      bullets: [
        "Anti-Corruption Layer: Wraps legacy databases behind standardized APIs, decoupling consumers from outdated schemas.",
        "Strangler Fig: Gradually replaces legacy functionality by building new capabilities natively in the mesh.",
        "Parallel Run: Validates correctness by running legacy and modern systems concurrently before decommissioning.",
        "The consumer experience never changes while the backend transparently shifts from on-prem to cloud.",
      ],
      mediaType: "card",
      mediaCardTitle: "Phased Modernization",
      mediaCardItems: [
        { label: "Phase 1", value: "API Wrapper (Anti-Corruption)" },
        { label: "Phase 2", value: "New Features (Strangler Fig)" },
        { label: "Phase 3", value: "Concurrent Ops (Parallel Run)" },
        { label: "Phase 4", value: "Decommission Legacy" },
      ],
      mediaCaption: "Modernization must be incremental to ensure operational continuity.",
    },
    {
      id: "slide-9",
      type: "featureGrid",
      title: "Tradeoffs & Challenges",
      subtitle: "A sociotechnical transformation requires shifting skills and trust alongside infrastructure.",
      category: "IMPLEMENTATION REALITIES",
      features: [
        {
          id: "f-1",
          title: "Organizational Disruption",
          description: "Shifting data responsibility generates cultural friction. Domain scientists may resist new management duties.",
          iconName: "Users",
          badge: "Culture",
          accentColor: "coral",
        },
        {
          id: "f-2",
          title: "Platform Investment",
          description: "Requires significant upfront infrastructure investment. FinOps is essential for cost attribution.",
          iconName: "DollarSign",
          badge: "FinOps",
          accentColor: "skygold",
        },
        {
          id: "f-3",
          title: "Governance Complexity",
          description: "Overly restrictive governance blocks use cases; overly permissive governance undermines compliance.",
          iconName: "Settings",
          badge: "Balance",
          accentColor: "seagrass",
        },
      ],
    },
    {
      id: "slide-10",
      type: "split",
      title: "Conclusion: Future-Ready Science",
      subtitle: "Improving NOAA Data Accessibility in a Modern Technology Landscape.",
      category: "WORKSHOP THEME",
      bullets: [
        "Data mesh resolves the tension between regional autonomy and enterprise integration.",
        "Future evolution will extend the platform to support ML workloads and AI-assisted discovery.",
        "Public data consumption could serve industry planning and research transparency via the same access models.",
        "The path from fragmentation to federation is 80% people, 20% technology.",
      ],
      mediaType: "card",
      mediaCardTitle: "Research Acknowledgement",
      mediaCardItems: [
        { label: "Origin", value: "Georgetown University" },
        { label: "Course 1", value: "MTPM 5750-1 (Enterprise Mod.)" },
        { label: "Course 2", value: "MTPM/MPIT 6656-01 (Cloud)" },
        { label: "Instructor", value: "Matthew Briggs" },
      ],
      mediaCaption: "Disclaimer: Views expressed are my own and do not represent official NOAA Fisheries policy.",
    },
  ],
};
